version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      # default user
      # POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'sample'
      POSTGRES_DB: 'sampledb'
    ports:
      - '5432:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d